name: Daily Pulse Automation

on:
  schedule:
    # 每天 UTC 时间 00:00 运行（对应北京时间早上 8:00）
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许你在网页端手动点击运行测试

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    # 赋予 GitHub Actions 推送代码回仓库的权限
    permissions:
      contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Script
      env:
        RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        RAPIDAPI_HOST: twitter241.p.rapidapi.com
        SEARCH_BASE_QUERY: '(AI OR "artificial intelligence" OR LLM OR "machine learning" OR OpenAI OR ChatGPT OR GenAI OR tech OR technology OR cybersecurity OR software OR startup OR SaaS OR "Silicon Valley" OR finance OR economy OR crypto OR "stock market" OR investing OR "Wall Street" OR macroeconomics OR politics OR geopolitics OR "foreign policy" OR "international relations" OR diplomacy OR elections OR POTUS) min_faves:500'
        OBSIDIAN_DIR: './notes'
        SMTP_SERVER: smtp.qq.com
        SMTP_PORT: 465
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
      run: python main.py

    - name: Commit and Push Markdown to Repo
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add notes/*.md
        git commit -m "Auto-generated Daily Pulse" || echo "No changes to commit"
        git push